version: "3"
services:
  app:
    container_name: containerize_app_1
    image: containerize_app
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app/src/server.py:/app/server.py
    ports: 
      - "8081:8000"

  nginx:
    container_name: containerize_nginx_1
    image: nginx
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/files/localhost.crt:/etc/ssl/certs/nginx.crt
      - ./nginx/files/localhost.key:/etc/ssl/private/nginx.key
    depends_on:
      - app
